### ISSUE TITLE
Change server port from 2815 to 2814

### ISSUE THREAD

**Issue by rassware** [ricaun/DuinoCoinI2C#10]
Actual port maps to 2815 which is the ESP mining port. But should it not be the port 2814 for AVR mining? The ESP is only the master for the communication. Right?

**Comment by ricaun** [comment]
Yes, you probably right. I goona check the AVR miner and verify if the port change or not.

**Comment by ricaun** [comment]
```
AVAILABLE_PORTS = [2813, 2814, 2816, 2812]
```
Gonna change and fix the issue...

**Comment by ricaun** [comment]
The multiport connection was fixed!
Thanks @rassware
