### ISSUE TITLE
Random Specified Ports (improvement)

### ISSUE THREAD

**Issue by modfiles** [ricaun/DuinoCoinI2C#11]
Any possibility to implement the joggling ports like the new feature of the official miners? and maybe an option to ping the server ip+ports if it will response, otherwise will choose on list of specified ports.

**Comment by ricaun** [comment]
I implemented exact that yesterday.
I added an array of available ports and each connection tries a port and goes to the next and so on.

**Comment by modfiles** [comment]
thanks, i happened to see the update and tested it but it stuck in connecting to server and connection failed loop for hours but prior to testing the latest update, all ports are working so atm, i switch to previous version

**Comment by emulatormania** [comment]
cant connect with random ports

**Comment by ricaun** [comment]
Thanks @rassware to fix the random port connection.
