### ISSUE TITLE
Connection failed with working server ports

### ISSUE THREAD

**Issue by spareartsa** [ricaun/DuinoCoinI2C#14]
connection failed the server ports are fine it just wont connect 
![f](https://user-images.githubusercontent.com/71305174/125180075-bdcdc080-e1aa-11eb-85c5-93ae96cf0f74.PNG)
![press f](https://user-images.githubusercontent.com/71305174/125180085-df2eac80-e1aa-11eb-8885-992c96bda8fb.PNG)

**Comment by ricaun** [comment]
You should try first with just one slave, your I2C connection looks really unstable.

Should stay equal every FreeRam loop.

**Comment by spareartsa** [comment]
![h](https://user-images.githubusercontent.com/71305174/126407582-36a1e9aa-c5fc-49a8-a67f-bc0d42d12d75.PNG)
