### ISSUE TITLE
Не получилось запустить код на mega 2560 pro mini

### ISSUE THREAD

**Issue by pinokio240** [ricaun/DuinoCoinI2C#17]
Не получилось запустить код на mega 2560 pro mini. Прошивается и не работает. Есть ли какая особенность при прошивке? Прошиваю  скетчем DuinoCoin_Arduino_Slave. Один раз даже прошил. Но ESP не работала с ним. В com в ком порт отладочная информация шла

**Comment by ricaun** [comment]
I do not understand what's happen, you are not able to compile the Arduino Mega? Or is not showing on the ESP serial monitor, consider check the I2C pins connection.

And I do not speak Russian, please write in English.
