### ISSUE TITLE
ive done everything in my knowledge to fix it

### ISSUE THREAD

**Issue by spareartsa** [ricaun/DuinoCoinI2C#19]
![idk](https://user-images.githubusercontent.com/71305174/126403008-29a93f66-cd58-433c-9709-211507ef7bec.PNG)

**Comment by ricaun** [comment]
Probably some connection on the I2C is not right, you should test with just one and see that happen.

**Comment by spareartsa** [comment]
![ok](https://user-images.githubusercontent.com/71305174/126405956-5fdb9d97-6218-4cac-90a9-1074f5ee8fdd.PNG)

**Comment by ricaun** [comment]
Something is bad with the I2C, the `Job Done:` should not return `(0)`.

Try to recompile the slave.

**Comment by spareartsa** [comment]
![h](https://user-images.githubusercontent.com/71305174/126407632-4e07b080-6cb4-496a-9ade-c0ffc98009fd.PNG)

**Comment by spareartsa** [comment]
join general in the server

**Comment by ricaun** [comment]
Something is bad on the I2C connection... The Connected should return always [ 0 ].

**Comment by spareartsa** [comment]
do you think putting all the arduinos on one crystal oscillator will fix it. cuz thay go out of sync

**Comment by ricaun** [comment]
> do you think putting all the arduinos on one crystal oscillator will fix it. cuz thay go out of sync

What? Who says that?

Check you i2c connection, you should re update the code and check wires and pins connection.
