### ISSUE TITLE
ATMega328 change to difficulty @16

### ISSUE THREAD

**Issue by PipeDeveloper** [ricaun/DuinoCoinI2C#20]
ATMega328 with the optimized duino-coin library do about 215-220 H/s, however the server interpret the device as the arduino mega.

The server interpret 190 H/s arround as a standard arduino with dificulty of @6
But with this code 220H/s server rise to dificulty of @16, affecting the reward (which it pays less) and the performance, less submits.

In the few days the performance of the reward has been drop in about 30-40% when usually i do 80-90 DUCO per day, now i do about 40-50 DUCO per day with the same setup.

![image](https://user-images.githubusercontent.com/35433329/126581592-a2c8f4e3-2d64-41d7-91cd-7162b7d6f711.png)

**Comment by ericddm** [comment]
I have the same problem as you, and what if i add 100ms delay to ATMega328？ 
I am gona try it

**Comment by ericddm** [comment]
![微信图片_20210722124608](https://user-images.githubusercontent.com/20798114/126591249-95252a2d-adb4-4dcb-8302-b8206b731fa5.jpg)

**Comment by ktannady** [comment]
does it work?

**Comment by ericddm** [comment]
> does it work?

https://github.com/revoxhere/duino-coin/issues/681
revoxhere has fixed that bug :)

**Comment by ktannady** [comment]
wow thanks! BTW really nice board!

**Comment by ricaun** [comment]
@ericddm nice board! Really cool!

@PipeDeveloper About the 215-220 H/s speed... The library uses a diferente encoder then the original project, I gonna create a new version on the library using the original encoder.

The job difficult probably gonna stay on 6.

**Comment by ricaun** [comment]
I update the library to the default encrypted, and the server now uses difficulty 4.

**Comment by Dendrobats** [comment]
This problem is back again on 2.7

**Comment by ricaun** [comment]
Yes something change on the server, gonna make some tests...
