### ISSUE TITLE
wemos d1 mini as slaves?

### ISSUE THREAD

**Issue by akasal** [ricaun/DuinoCoinI2C#25]
They're really cheap. I was wondering if the slave code would work on the wmos d1 mini 8266 (clone).

Thanks.

**Comment by akasal** [comment]
I ordered some, will test it and report back.

**Comment by mrgh14** [comment]
hi

> 

- 

@1. please give me advantege

**Comment by ricaun** [comment]
> They're really cheap. I was wondering if the slave code would work on the wmos d1 mini 8266 (clone).
> 
> Thanks.

Make no sense to use a esp8266 like a slave, If you have a bunch of esp8266 you should use to mine directly.

A slave should be a device without internet connection.

Check the Esp code on the main DuinoCoin project.

https://github.com/revoxhere/duino-coin
