### ISSUE TITLE
need update to revoxhere/duino-coin v2.6

### ISSUE THREAD

**Issue by panayotovip** [ricaun/DuinoCoinI2C#29]
After update from revoxhere/duino-coin to v2.6 stand alone nanos work no problems.
Here is running AVR I2C v2.5.2 and it is a lot of troubles with nodes.

Please do update and add if you can add serial monitor over network.

**Comment by jonnycn** [comment]
Please do update~!

**Comment by PipeDeveloper** [comment]
+1

**Comment by oli737** [comment]
Please update, isn't working anymore.

**Comment by Froster69** [comment]
please update- ̗̀(๑ᵔ⌔ᵔ๑)

**Comment by ktannady** [comment]
please update :D

**Comment by panayotovip** [comment]
hey dudes look what i found :
https://github.com/AzagraMac/DuinoCoin_I2C
i do not tested that still

**Comment by ricaun** [comment]
Yes, something is always changing on the main DuinoCoin project...

**Comment by oli737** [comment]
> hey dudes look what i found :
> https://github.com/AzagraMac/DuinoCoin_I2C
> i do not tested that still

This one is not working you did not check the issue i opend on that.

**Comment by ricaun** [comment]
The server is not sending jobs when the esp requests... 

I need to check the https://github.com/revoxhere/duino-coin/blob/master/AVR_Miner.py

**Comment by panayotovip** [comment]
> 
> 
> > hey dudes look what i found :
> > https://github.com/AzagraMac/DuinoCoin_I2C
> > i do not tested that still
> 
> This one is not working you did not check the issue i opend on that.

did not have time when i found it.
thanks for testing.

**Comment by panayotovip** [comment]
every thing is up and running ok
thankU-for-GJ ricaun

**Comment by ericddm** [comment]
> every thing is up and running ok
> thankU-for-GJ ricaun

I got about 10 coins a day by 6 Arduino Nano,  is that ok?

**Comment by ricaun** [comment]
> > every thing is up and running ok
> > thankU-for-GJ ricaun
> 
> I got about 10 coins a day by 6 Arduino Nano, is that ok?

I don't know, maybe the I2C is not so profit or the server is a little inconsistent.

**Comment by ricaun** [comment]
The project now works on version 2.6.
