### ISSUE TITLE
update the picture with OLED and thanks to ricaun

### ISSUE THREAD

**Issue by ericddm** [ricaun/DuinoCoinI2C#33]
very great job, thank you,ricaun.
![微信图片_20210807002137](https://user-images.githubusercontent.com/20798114/128542750-8de24c7b-fe8d-4450-aa9e-d3270273f172.jpg)

**Comment by panayotovip** [comment]
it look amazing !

**Comment by pinokio240** [comment]
> very great job, thank you,ricaun.
> ![微信图片_20210807002137](https://user-images.githubusercontent.com/20798114/128542750-8de24c7b-fe8d-4450-aa9e-d3270273f172.jpg)

Здравствуйте. Вы сами делали эту плату? Я правельно понимаю что сдесь ESP8266? Кокая у Вас  операционная система и версия питна? Есть ли дополнительные программы кроме ArduinoIDE?

**Comment by ericddm** [comment]
> > very great job, thank you,ricaun.
> > ![微信图片_20210807002137](https://user-images.githubusercontent.com/20798114/128542750-8de24c7b-fe8d-4450-aa9e-d3270273f172.jpg)
> 
> Здравствуйте. Вы сами делали эту плату? Я правельно понимаю что сдесь ESP8266? Кокая у Вас операционная система и версия питона? Есть ли дополнительные программы кроме ArduinoIDE?

Привет, мой друг. Я сам сделал эту доску. Он содержит один ESP8266 и 6 Mega328P. Мне нужно только установить ArduinoIDE, чтобы он заработал.
[ESP8266ArduinoNano6CoreDuinoMinerPCB.zip](https://github.com/ricaun/DuinoCoinI2C/files/6949361/ESP8266ArduinoNano6CoreDuinoMinerPCB.zip)

PCB files can be opened with Pads software,
_blz is a file that has been automatically routed and can be processed directly, 
and asc files can be imported with AltiumDesign.
![无标题](https://user-images.githubusercontent.com/20798114/128606413-c4562ff5-adfa-4d17-ae60-67bc7e7a9808.png)

**Comment by ricaun** [comment]
> very great job, thank you,ricaun.
> ![微信图片_20210807002137](https://user-images.githubusercontent.com/20798114/128542750-8de24c7b-fe8d-4450-aa9e-d3270273f172.jpg)

Cool, @ericddm you should create a github project with pictures, schematic, files and so on.
