### ISSUE TITLE
The miner does not work.

### ISSUE THREAD

**Issue by pinokio240** [ricaun/DuinoCoinI2C#44]
The miner does not work.
 After the last events on the server. revoxhere corrected something. Although the ESP code works from it. You can check why his code works and yours does not. The miner connects to the server but does not get work

**Comment by oli737** [comment]
It's because AVR was disabled last days. Version 2.7 is out already. We are waiting for update.

**Comment by ricaun** [comment]
Try to update the esp code that should work on the version 2.7.

At the moment the duinocoin server is no working...
