### ISSUE TITLE
Can Atmega168 Arduino Nano be used as slave?

### ISSUE THREAD

**Issue by hengchau** [ricaun/DuinoCoinI2C#5]
I want to order some nano's but wonder if Atmega168 are usable? Possibly also in the long run?
Thanks!

**Comment by qazwsx1212notdead** [comment]
yes, there will be no problems

**Comment by hengchau** [comment]
thanks!

**Comment by Hagbard89** [comment]
i got some Atmega168 nanos, but i can't get them working, i receive a job, but then "i2c freeram" and "Timeout" message in the serial monitor...
