### ISSUE TITLE
Max slave number

### ISSUE THREAD

**Issue by CN-Antonio** [ricaun/DuinoCoinI2C#51]
I'm making an AIO board including ESP8266 as master and Atmega328p as slave. I wonder the max number of slave is 10 in README or can be higher?  If it's more than 10, it would be better. :)

**Comment by ricaun** [comment]
You could change the define.
```
#define CLIENTS 10
```
And set to another number, but I don't know if the ESP8266 can handle too many devices at the same time.

**Comment by CN-Antonio** [comment]
Got it, I'll try. Thanks :)
