### ISSUE TITLE
Doesn't connect to DUCO server

### ISSUE THREAD

**Issue by pinokio240** [ricaun/DuinoCoinI2C#72]
Stopped connecting to the server to get work. Internet connection is present, no additional settings have been made in the router
![fetysrtyrtyhsthstdgjhsfrtjhryjrsy](https://user-images.githubusercontent.com/37944152/148074453-038869bb-93dc-4dfa-95b1-757391c2f205.jpg)

**Comment by tzalus** [comment]
Just built my miner (esp8622+7nanos) and I'm getting the same thing in serial monitor. Put the standard duino coin code on the esp and it works fine... Back to i2c version connection failed.

**Comment by ricaun** [comment]
The `urlPool` need to be updated. The last version updates and fix this issue.
