### ISSUE TITLE
Hi and  how to change uniqueid on pro mini 328 ?

### ISSUE THREAD

**Issue by lyovav** [ricaun/DuinoCoinI2C#74]
I have a few chips, I read the same thing like

UniqueID: FF DF FF DF FF FF FF FF 
Wire Address: 1

**Comment by ricaun** [comment]
Is not possible to change, this number is embedded when the chip is fabricated.

Your chip probably is a counterfeit, this number is not guaranteed to be unique, a counterfeit atmega328p usually has the same number.

Check the video: https://www.youtube.com/watch?v=eeDC1m7ANJI
