### ISSUE TITLE
 duino-coin  Release 3.0

### ISSUE THREAD

**Issue by MiloPS3** [ricaun/DuinoCoinI2C#77]
Hi, are you planning to upgrade DuinoCoinI2C ? 

> _upgrading to this release is required. Servers will stop accepting version 2.X miners in a few weeks._

**Comment by ricaun** [comment]
I need to take a look at the new Release. 😭

**Comment by JoJos1220** [comment]
Lets do it!

**Comment by JoJos1220** [comment]
> Hi, are you planning to upgrade DuinoCoinI2C ?
> 
> > _upgrading to this release is required. Servers will stop accepting version 2.X miners in a few weeks._

Maybe only changing the "Miner Version" in the I2C Software to 3.0 and thats it ;)

**Comment by malloc32** [comment]
We can't mine using this project?

19:05:30.229 -> [ ]FreeRam: 39056 I2C [ 0. ]
19:05:30.839 -> [0]Job BAD,Outdated miner: Share #11 0:01:34

Thank you.

**Comment by malloc32** [comment]
Thank you very much.

**Comment by ricaun** [comment]
I don't know what changed... 😑

**Comment by sabreman79** [comment]
Yeah, I guess they flipped the switch last night. I was mining happily, then BAM nothing. I'm a little dissapointed since I just finished my rig a couple of days ago :(

**Comment by ricaun** [comment]
@revoxhere change some checks on the server, now should work.

The problem basically was related with the `rigIdentifier`.
